yolo:
  type: "yolov3_tiny"
  iou_threshold: 0.5
  score_threshold: 0.5
  max_boxes: 100
  strides: "32,16"
  anchors: "23,27 37,58 81,82 81,82 135,169 344,319"
  mask: "3,4,5 0,1,2"


train:
  label: "yolov3_tiny"

  image_size: "320,352,384,416,448,480,512,544,576,608"


  loss_type: "CIoU+FL"
  mosaic: false
  label_smoothing: false
  normal_method: true
  ignore_threshold: 0.7

test:

  image_size: "416"
  batch_size: 1

